# Generated by Django 5.2.4 on 2025-08-06 02:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0001_initial'),
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.PositiveIntegerField()),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('otro', 'Otro')], default='efectivo', max_length=15)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pagado', max_length=10)),
                ('fecha_pago', models.DateField(default=datetime.date.today)),
                ('observacion', models.TextField(blank=True, default='Sin observaciones')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='actividades.actividad')),
                ('apoderado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuotas', to='cuotas.apoderado')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='estudiantes.estudiante')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
