# Generated by Django 5.2.4 on 2025-08-06 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('curso', models.ForeignKey(blank=True, help_text='Curso al que está asociada la actividad', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades_generales', to='estudiantes.curso')),
            ],
        ),
    ]
